services:
  dev:
    image: dev_env
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        DEVCONTAINER_OS_IMAGE: ${DEVCONTAINER_OS_IMAGE}
        PYTHON_VERSION: ${PYTHON_VERSION}
        R_VERSION: ${R_VERSION}
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
        DEV_ENV_LOCKED: ${DEV_ENV_LOCKED:-0}
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      TZ: ${TZ:-UTC}
      HOST_DATA_DIR: ${HOST_DATA_DIR:-}
      HOST_DATA_MOUNT_PATH: ${HOST_DATA_MOUNT_PATH:-/home/dev/data_external}
      PYTHON_VERSION: ${PYTHON_VERSION}
      R_VERSION: ${R_VERSION}
      HOST_DATA_SYMLINK_PATH: ${HOST_DATA_SYMLINK_PATH:-/home/dev/dev_container/workspace/data_external}
    volumes:
      - ../..:/home/dev/dev_container
    working_dir: /home/dev/dev_container
    tty: true
    stdin_open: true
    ports:
      - "${JUPYTER_PORT}:${JUPYTER_PORT}" # Expose JupyterLab port (host:container)
      - "${QUARTO_PORT}:${QUARTO_PORT}" # Expose Quarto preview port (host:container)
      - "${WEB_APP_PORT}:${WEB_APP_PORT}" # Expose web application dev server port (host:container)
    container_name: dev_env_container
