services:
  dev:
    env_file:
      - ../env-vars/.env
      - ../env-vars/.env.secrets
    image: dev_env
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        DEVCONTAINER_OS_IMAGE: ${DEVCONTAINER_OS_IMAGE}
        USER_UID: ${UID}
        USER_GID: ${GID}
        DEV_ENV_LOCKED: ${DEV_ENV_LOCKED}
    user: "${UID}:${GID}"
    volumes:
      - ../..:/home/dev/dev_container
    working_dir: /home/dev/dev_container
    tty: true
    stdin_open: true
    ports:
      - "${JUPYTER_PORT}:${JUPYTER_PORT}" # Expose JupyterLab port (host:container)
      - "${QUARTO_PORT}:${QUARTO_PORT}" # Expose Quarto preview port (host:container)
      - "${WEB_APP_PORT}:${WEB_APP_PORT}" # Expose web application dev server port (host:container)
    container_name: dev_env_container
